// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: sharedpb/shared.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interests) Reset() {
	*x = Interests{}
	mi := &file_sharedpb_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interests) ProtoMessage() {}

func (x *Interests) ProtoReflect() protoreflect.Message {
	mi := &file_sharedpb_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interests.ProtoReflect.Descriptor instead.
func (*Interests) Descriptor() ([]byte, []int) {
	return file_sharedpb_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Interests) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_sharedpb_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_sharedpb_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_sharedpb_shared_proto_rawDescGZIP(), []int{1}
}

func (x *Language) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Language      []*Language            `protobuf:"bytes,4,rep,name=language,proto3" json:"language,omitempty"`
	Interests     []*Interests           `protobuf:"bytes,5,rep,name=interests,proto3" json:"interests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sharedpb_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sharedpb_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sharedpb_shared_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetLanguage() []*Language {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *User) GetInterests() []*Interests {
	if x != nil {
		return x.Interests
	}
	return nil
}

var File_sharedpb_shared_proto protoreflect.FileDescriptor

const file_sharedpb_shared_proto_rawDesc = "" +
	"\n" +
	"\x15sharedpb/shared.proto\x12\bsharedpb\"\x1f\n" +
	"\tInterests\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\bLanguage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb1\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12.\n" +
	"\blanguage\x18\x04 \x03(\v2\x12.sharedpb.LanguageR\blanguage\x121\n" +
	"\tinterests\x18\x05 \x03(\v2\x13.sharedpb.InterestsR\tinterestsB@Z>github.com/chimort/course_project2/api/proto/sharedpb;sharedpbb\x06proto3"

var (
	file_sharedpb_shared_proto_rawDescOnce sync.Once
	file_sharedpb_shared_proto_rawDescData []byte
)

func file_sharedpb_shared_proto_rawDescGZIP() []byte {
	file_sharedpb_shared_proto_rawDescOnce.Do(func() {
		file_sharedpb_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sharedpb_shared_proto_rawDesc), len(file_sharedpb_shared_proto_rawDesc)))
	})
	return file_sharedpb_shared_proto_rawDescData
}

var file_sharedpb_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sharedpb_shared_proto_goTypes = []any{
	(*Interests)(nil), // 0: sharedpb.Interests
	(*Language)(nil),  // 1: sharedpb.Language
	(*User)(nil),      // 2: sharedpb.User
}
var file_sharedpb_shared_proto_depIdxs = []int32{
	1, // 0: sharedpb.User.language:type_name -> sharedpb.Language
	0, // 1: sharedpb.User.interests:type_name -> sharedpb.Interests
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sharedpb_shared_proto_init() }
func file_sharedpb_shared_proto_init() {
	if File_sharedpb_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sharedpb_shared_proto_rawDesc), len(file_sharedpb_shared_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sharedpb_shared_proto_goTypes,
		DependencyIndexes: file_sharedpb_shared_proto_depIdxs,
		MessageInfos:      file_sharedpb_shared_proto_msgTypes,
	}.Build()
	File_sharedpb_shared_proto = out.File
	file_sharedpb_shared_proto_goTypes = nil
	file_sharedpb_shared_proto_depIdxs = nil
}
