// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: api/proto/chatpb/chat.proto

package chatpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *CreateChatRequest) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatpb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ListUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chatpb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserChatsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ChatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Participants  []string               `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInfo) Reset() {
	*x = ChatInfo{}
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInfo) ProtoMessage() {}

func (x *ChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInfo.ProtoReflect.Descriptor instead.
func (*ChatInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_chatpb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatInfo) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatInfo) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatInfo            `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chatpb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chatpb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserChatsResponse) GetChats() []*ChatInfo {
	if x != nil {
		return x.Chats
	}
	return nil
}

var File_api_proto_chatpb_chat_proto protoreflect.FileDescriptor

const file_api_proto_chatpb_chat_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/chatpb/chat.proto\x12\x06chatpb\x1a\x1cgoogle/api/annotations.proto\"?\n" +
	"\x11CreateChatRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"=\n" +
	"\x12CreateChatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"*\n" +
	"\x14ListUserChatsRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"G\n" +
	"\bChatInfo\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\"\n" +
	"\fparticipants\x18\x02 \x03(\tR\fparticipants\"?\n" +
	"\x15ListUserChatsResponse\x12&\n" +
	"\x05chats\x18\x01 \x03(\v2\x10.chatpb.ChatInfoR\x05chats2\xd5\x01\n" +
	"\vChatService\x12X\n" +
	"\n" +
	"CreateChat\x12\x19.chatpb.CreateChatRequest\x1a\x1a.chatpb.CreateChatResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/chat\x12l\n" +
	"\rListUserChats\x12\x1c.chatpb.ListUserChatsRequest\x1a\x1d.chatpb.ListUserChatsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/users/{user}/chatsB5Z3github.com/chimort/course_project2/api/proto/chatpbb\x06proto3"

var (
	file_api_proto_chatpb_chat_proto_rawDescOnce sync.Once
	file_api_proto_chatpb_chat_proto_rawDescData []byte
)

func file_api_proto_chatpb_chat_proto_rawDescGZIP() []byte {
	file_api_proto_chatpb_chat_proto_rawDescOnce.Do(func() {
		file_api_proto_chatpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chatpb_chat_proto_rawDesc), len(file_api_proto_chatpb_chat_proto_rawDesc)))
	})
	return file_api_proto_chatpb_chat_proto_rawDescData
}

var file_api_proto_chatpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_chatpb_chat_proto_goTypes = []any{
	(*CreateChatRequest)(nil),     // 0: chatpb.CreateChatRequest
	(*CreateChatResponse)(nil),    // 1: chatpb.CreateChatResponse
	(*ListUserChatsRequest)(nil),  // 2: chatpb.ListUserChatsRequest
	(*ChatInfo)(nil),              // 3: chatpb.ChatInfo
	(*ListUserChatsResponse)(nil), // 4: chatpb.ListUserChatsResponse
}
var file_api_proto_chatpb_chat_proto_depIdxs = []int32{
	3, // 0: chatpb.ListUserChatsResponse.chats:type_name -> chatpb.ChatInfo
	0, // 1: chatpb.ChatService.CreateChat:input_type -> chatpb.CreateChatRequest
	2, // 2: chatpb.ChatService.ListUserChats:input_type -> chatpb.ListUserChatsRequest
	1, // 3: chatpb.ChatService.CreateChat:output_type -> chatpb.CreateChatResponse
	4, // 4: chatpb.ChatService.ListUserChats:output_type -> chatpb.ListUserChatsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_chatpb_chat_proto_init() }
func file_api_proto_chatpb_chat_proto_init() {
	if File_api_proto_chatpb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chatpb_chat_proto_rawDesc), len(file_api_proto_chatpb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chatpb_chat_proto_goTypes,
		DependencyIndexes: file_api_proto_chatpb_chat_proto_depIdxs,
		MessageInfos:      file_api_proto_chatpb_chat_proto_msgTypes,
	}.Build()
	File_api_proto_chatpb_chat_proto = out.File
	file_api_proto_chatpb_chat_proto_goTypes = nil
	file_api_proto_chatpb_chat_proto_depIdxs = nil
}
