// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: chatpb/chat.proto

package chatpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *CreateChatRequest) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type SendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Sender          string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType     string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	FileUrl         string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName        string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType        string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSizeBytes   int64                  `protobuf:"varint,8,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendMessageRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SendMessageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendMessageRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SendMessageRequest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *SendMessageRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsRequest) Reset() {
	*x = GetParticipantsRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsRequest) ProtoMessage() {}

func (x *GetParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetParticipantsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParticipantsResponse) Reset() {
	*x = GetParticipantsResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParticipantsResponse) ProtoMessage() {}

func (x *GetParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetParticipantsResponse) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sender          string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content         string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MessageType     string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	FileUrl         string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName        string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType        string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSizeBytes   int64                  `protobuf:"varint,8,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatpb_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ChatMessage) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ChatMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ChatMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ChatMessage) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *ChatMessage) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	FilterMode    string                 `protobuf:"bytes,3,opt,name=filter_mode,json=filterMode,proto3" json:"filter_mode,omitempty"`
	FilterTag     string                 `protobuf:"bytes,4,opt,name=filter_tag,json=filterTag,proto3" json:"filter_tag,omitempty"`
	PeerQuery     string                 `protobuf:"bytes,5,opt,name=peer_query,json=peerQuery,proto3" json:"peer_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsRequest) Reset() {
	*x = GetUserChatsRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsRequest) ProtoMessage() {}

func (x *GetUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserChatsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserChatsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetUserChatsRequest) GetFilterMode() string {
	if x != nil {
		return x.FilterMode
	}
	return ""
}

func (x *GetUserChatsRequest) GetFilterTag() string {
	if x != nil {
		return x.FilterTag
	}
	return ""
}

func (x *GetUserChatsRequest) GetPeerQuery() string {
	if x != nil {
		return x.PeerQuery
	}
	return ""
}

type ChatPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PeerUsername  string                 `protobuf:"bytes,2,opt,name=peer_username,json=peerUsername,proto3" json:"peer_username,omitempty"`
	LastMessage   string                 `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMessageAt string                 `protobuf:"bytes,4,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	HasUnread     bool                   `protobuf:"varint,5,opt,name=has_unread,json=hasUnread,proto3" json:"has_unread,omitempty"`
	MatchHint     string                 `protobuf:"bytes,6,opt,name=match_hint,json=matchHint,proto3" json:"match_hint,omitempty"`
	MatchTags     []string               `protobuf:"bytes,7,rep,name=match_tags,json=matchTags,proto3" json:"match_tags,omitempty"`
	SearchMode    string                 `protobuf:"bytes,8,opt,name=search_mode,json=searchMode,proto3" json:"search_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPreview) Reset() {
	*x = ChatPreview{}
	mi := &file_chatpb_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPreview) ProtoMessage() {}

func (x *ChatPreview) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPreview.ProtoReflect.Descriptor instead.
func (*ChatPreview) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ChatPreview) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatPreview) GetPeerUsername() string {
	if x != nil {
		return x.PeerUsername
	}
	return ""
}

func (x *ChatPreview) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *ChatPreview) GetLastMessageAt() string {
	if x != nil {
		return x.LastMessageAt
	}
	return ""
}

func (x *ChatPreview) GetHasUnread() bool {
	if x != nil {
		return x.HasUnread
	}
	return false
}

func (x *ChatPreview) GetMatchHint() string {
	if x != nil {
		return x.MatchHint
	}
	return ""
}

func (x *ChatPreview) GetMatchTags() []string {
	if x != nil {
		return x.MatchTags
	}
	return nil
}

func (x *ChatPreview) GetSearchMode() string {
	if x != nil {
		return x.SearchMode
	}
	return ""
}

type GetUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatPreview         `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsResponse) Reset() {
	*x = GetUserChatsResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsResponse) ProtoMessage() {}

func (x *GetUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserChatsResponse) GetChats() []*ChatPreview {
	if x != nil {
		return x.Chats
	}
	return nil
}

type MarkChatReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatReadRequest) Reset() {
	*x = MarkChatReadRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadRequest) ProtoMessage() {}

func (x *MarkChatReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadRequest.ProtoReflect.Descriptor instead.
func (*MarkChatReadRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{12}
}

func (x *MarkChatReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MarkChatReadRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type MarkChatReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatReadResponse) Reset() {
	*x = MarkChatReadResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadResponse) ProtoMessage() {}

func (x *MarkChatReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadResponse.ProtoReflect.Descriptor instead.
func (*MarkChatReadResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{13}
}

func (x *MarkChatReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetChatMatchTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	SearchMode    string                 `protobuf:"bytes,3,opt,name=search_mode,json=searchMode,proto3" json:"search_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChatMatchTagsRequest) Reset() {
	*x = SetChatMatchTagsRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChatMatchTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChatMatchTagsRequest) ProtoMessage() {}

func (x *SetChatMatchTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChatMatchTagsRequest.ProtoReflect.Descriptor instead.
func (*SetChatMatchTagsRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{14}
}

func (x *SetChatMatchTagsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SetChatMatchTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SetChatMatchTagsRequest) GetSearchMode() string {
	if x != nil {
		return x.SearchMode
	}
	return ""
}

type SetChatMatchTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChatMatchTagsResponse) Reset() {
	*x = SetChatMatchTagsResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChatMatchTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChatMatchTagsResponse) ProtoMessage() {}

func (x *SetChatMatchTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChatMatchTagsResponse.ProtoReflect.Descriptor instead.
func (*SetChatMatchTagsResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{15}
}

func (x *SetChatMatchTagsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BlockUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockerUsername string                 `protobuf:"bytes,1,opt,name=blocker_username,json=blockerUsername,proto3" json:"blocker_username,omitempty"`
	BlockedUsername string                 `protobuf:"bytes,2,opt,name=blocked_username,json=blockedUsername,proto3" json:"blocked_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{16}
}

func (x *BlockUserRequest) GetBlockerUsername() string {
	if x != nil {
		return x.BlockerUsername
	}
	return ""
}

func (x *BlockUserRequest) GetBlockedUsername() string {
	if x != nil {
		return x.BlockedUsername
	}
	return ""
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{17}
}

func (x *BlockUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetBlockStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         string                 `protobuf:"bytes,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         string                 `protobuf:"bytes,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockStatusRequest) Reset() {
	*x = GetBlockStatusRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStatusRequest) ProtoMessage() {}

func (x *GetBlockStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBlockStatusRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{18}
}

func (x *GetBlockStatusRequest) GetUser1() string {
	if x != nil {
		return x.User1
	}
	return ""
}

func (x *GetBlockStatusRequest) GetUser2() string {
	if x != nil {
		return x.User2
	}
	return ""
}

type GetBlockStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsBlocked      bool                   `protobuf:"varint,1,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	BlockedByUser1 bool                   `protobuf:"varint,2,opt,name=blocked_by_user1,json=blockedByUser1,proto3" json:"blocked_by_user1,omitempty"`
	BlockedByUser2 bool                   `protobuf:"varint,3,opt,name=blocked_by_user2,json=blockedByUser2,proto3" json:"blocked_by_user2,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlockStatusResponse) Reset() {
	*x = GetBlockStatusResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockStatusResponse) ProtoMessage() {}

func (x *GetBlockStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBlockStatusResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlockStatusResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *GetBlockStatusResponse) GetBlockedByUser1() bool {
	if x != nil {
		return x.BlockedByUser1
	}
	return false
}

func (x *GetBlockStatusResponse) GetBlockedByUser2() bool {
	if x != nil {
		return x.BlockedByUser2
	}
	return false
}

type UnblockUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockerUsername string                 `protobuf:"bytes,1,opt,name=blocker_username,json=blockerUsername,proto3" json:"blocker_username,omitempty"`
	BlockedUsername string                 `protobuf:"bytes,2,opt,name=blocked_username,json=blockedUsername,proto3" json:"blocked_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnblockUserRequest) Reset() {
	*x = UnblockUserRequest{}
	mi := &file_chatpb_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserRequest) ProtoMessage() {}

func (x *UnblockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserRequest.ProtoReflect.Descriptor instead.
func (*UnblockUserRequest) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{20}
}

func (x *UnblockUserRequest) GetBlockerUsername() string {
	if x != nil {
		return x.BlockerUsername
	}
	return ""
}

func (x *UnblockUserRequest) GetBlockedUsername() string {
	if x != nil {
		return x.BlockedUsername
	}
	return ""
}

type UnblockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResponse) Reset() {
	*x = UnblockUserResponse{}
	mi := &file_chatpb_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResponse) ProtoMessage() {}

func (x *UnblockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatpb_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResponse.ProtoReflect.Descriptor instead.
func (*UnblockUserResponse) Descriptor() ([]byte, []int) {
	return file_chatpb_chat_proto_rawDescGZIP(), []int{21}
}

func (x *UnblockUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_chatpb_chat_proto protoreflect.FileDescriptor

const file_chatpb_chat_proto_rawDesc = "" +
	"\n" +
	"\x11chatpb/chat.proto\x12\x06chatpb\x1a\x1cgoogle/api/annotations.proto\"?\n" +
	"\x11CreateChatRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"-\n" +
	"\x12CreateChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xaa\x02\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12&\n" +
	"\x0ffile_size_bytes\x18\b \x01(\x03R\rfileSizeBytes\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x05R\x0fdurationSeconds\"%\n" +
	"\x13SendMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"1\n" +
	"\x16GetParticipantsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"7\n" +
	"\x17GetParticipantsResponse\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames\"C\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa9\x02\n" +
	"\vChatMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12&\n" +
	"\x0ffile_size_bytes\x18\b \x01(\x03R\rfileSizeBytes\x12)\n" +
	"\x10duration_seconds\x18\t \x01(\x05R\x0fdurationSeconds\"F\n" +
	"\x13GetMessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.chatpb.ChatMessageR\bmessages\"\xa9\x01\n" +
	"\x13GetUserChatsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x1f\n" +
	"\vfilter_mode\x18\x03 \x01(\tR\n" +
	"filterMode\x12\x1d\n" +
	"\n" +
	"filter_tag\x18\x04 \x01(\tR\tfilterTag\x12\x1d\n" +
	"\n" +
	"peer_query\x18\x05 \x01(\tR\tpeerQuery\"\x94\x02\n" +
	"\vChatPreview\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12#\n" +
	"\rpeer_username\x18\x02 \x01(\tR\fpeerUsername\x12!\n" +
	"\flast_message\x18\x03 \x01(\tR\vlastMessage\x12&\n" +
	"\x0flast_message_at\x18\x04 \x01(\tR\rlastMessageAt\x12\x1d\n" +
	"\n" +
	"has_unread\x18\x05 \x01(\bR\thasUnread\x12\x1d\n" +
	"\n" +
	"match_hint\x18\x06 \x01(\tR\tmatchHint\x12\x1d\n" +
	"\n" +
	"match_tags\x18\a \x03(\tR\tmatchTags\x12\x1f\n" +
	"\vsearch_mode\x18\b \x01(\tR\n" +
	"searchMode\"A\n" +
	"\x14GetUserChatsResponse\x12)\n" +
	"\x05chats\x18\x01 \x03(\v2\x13.chatpb.ChatPreviewR\x05chats\"J\n" +
	"\x13MarkChatReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"&\n" +
	"\x14MarkChatReadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"g\n" +
	"\x17SetChatMatchTagsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x1f\n" +
	"\vsearch_mode\x18\x03 \x01(\tR\n" +
	"searchMode\"*\n" +
	"\x18SetChatMatchTagsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"h\n" +
	"\x10BlockUserRequest\x12)\n" +
	"\x10blocker_username\x18\x01 \x01(\tR\x0fblockerUsername\x12)\n" +
	"\x10blocked_username\x18\x02 \x01(\tR\x0fblockedUsername\"#\n" +
	"\x11BlockUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"C\n" +
	"\x15GetBlockStatusRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\tR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\tR\x05user2\"\x8b\x01\n" +
	"\x16GetBlockStatusResponse\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x01 \x01(\bR\tisBlocked\x12(\n" +
	"\x10blocked_by_user1\x18\x02 \x01(\bR\x0eblockedByUser1\x12(\n" +
	"\x10blocked_by_user2\x18\x03 \x01(\bR\x0eblockedByUser2\"j\n" +
	"\x12UnblockUserRequest\x12)\n" +
	"\x10blocker_username\x18\x01 \x01(\tR\x0fblockerUsername\x12)\n" +
	"\x10blocked_username\x18\x02 \x01(\tR\x0fblockedUsername\"%\n" +
	"\x13UnblockUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe7\b\n" +
	"\vChatService\x12_\n" +
	"\n" +
	"CreateChat\x12\x19.chatpb.CreateChatRequest\x1a\x1a.chatpb.CreateChatResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/chat/create\x12`\n" +
	"\vSendMessage\x12\x1a.chatpb.SendMessageRequest\x1a\x1b.chatpb.SendMessageResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/chat/send\x12{\n" +
	"\x0fGetParticipants\x12\x1e.chatpb.GetParticipantsRequest\x1a\x1f.chatpb.GetParticipantsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/chat/{chat_id}/participants\x12k\n" +
	"\vGetMessages\x12\x1a.chatpb.GetMessagesRequest\x1a\x1b.chatpb.GetMessagesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/chat/{chat_id}/messages\x12n\n" +
	"\fGetUserChats\x12\x1b.chatpb.GetUserChatsRequest\x1a\x1c.chatpb.GetUserChatsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/chat/history/{username}\x12x\n" +
	"\fMarkChatRead\x12\x1b.chatpb.MarkChatReadRequest\x1a\x1c.chatpb.MarkChatReadResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/chat/{chat_id}/read/{username}\x12\x7f\n" +
	"\x10SetChatMatchTags\x12\x1f.chatpb.SetChatMatchTagsRequest\x1a .chatpb.SetChatMatchTagsResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/chat/{chat_id}/match-tags\x12[\n" +
	"\tBlockUser\x12\x18.chatpb.BlockUserRequest\x1a\x19.chatpb.BlockUserResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/chat/block\x12~\n" +
	"\x0eGetBlockStatus\x12\x1d.chatpb.GetBlockStatusRequest\x1a\x1e.chatpb.GetBlockStatusResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/chat/block-status/{user1}/{user2}\x12c\n" +
	"\vUnblockUser\x12\x1a.chatpb.UnblockUserRequest\x1a\x1b.chatpb.UnblockUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/chat/unblockB5Z3github.com/chimort/course_project2/api/proto/chatpbb\x06proto3"

var (
	file_chatpb_chat_proto_rawDescOnce sync.Once
	file_chatpb_chat_proto_rawDescData []byte
)

func file_chatpb_chat_proto_rawDescGZIP() []byte {
	file_chatpb_chat_proto_rawDescOnce.Do(func() {
		file_chatpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatpb_chat_proto_rawDesc), len(file_chatpb_chat_proto_rawDesc)))
	})
	return file_chatpb_chat_proto_rawDescData
}

var file_chatpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_chatpb_chat_proto_goTypes = []any{
	(*CreateChatRequest)(nil),        // 0: chatpb.CreateChatRequest
	(*CreateChatResponse)(nil),       // 1: chatpb.CreateChatResponse
	(*SendMessageRequest)(nil),       // 2: chatpb.SendMessageRequest
	(*SendMessageResponse)(nil),      // 3: chatpb.SendMessageResponse
	(*GetParticipantsRequest)(nil),   // 4: chatpb.GetParticipantsRequest
	(*GetParticipantsResponse)(nil),  // 5: chatpb.GetParticipantsResponse
	(*GetMessagesRequest)(nil),       // 6: chatpb.GetMessagesRequest
	(*ChatMessage)(nil),              // 7: chatpb.ChatMessage
	(*GetMessagesResponse)(nil),      // 8: chatpb.GetMessagesResponse
	(*GetUserChatsRequest)(nil),      // 9: chatpb.GetUserChatsRequest
	(*ChatPreview)(nil),              // 10: chatpb.ChatPreview
	(*GetUserChatsResponse)(nil),     // 11: chatpb.GetUserChatsResponse
	(*MarkChatReadRequest)(nil),      // 12: chatpb.MarkChatReadRequest
	(*MarkChatReadResponse)(nil),     // 13: chatpb.MarkChatReadResponse
	(*SetChatMatchTagsRequest)(nil),  // 14: chatpb.SetChatMatchTagsRequest
	(*SetChatMatchTagsResponse)(nil), // 15: chatpb.SetChatMatchTagsResponse
	(*BlockUserRequest)(nil),         // 16: chatpb.BlockUserRequest
	(*BlockUserResponse)(nil),        // 17: chatpb.BlockUserResponse
	(*GetBlockStatusRequest)(nil),    // 18: chatpb.GetBlockStatusRequest
	(*GetBlockStatusResponse)(nil),   // 19: chatpb.GetBlockStatusResponse
	(*UnblockUserRequest)(nil),       // 20: chatpb.UnblockUserRequest
	(*UnblockUserResponse)(nil),      // 21: chatpb.UnblockUserResponse
}
var file_chatpb_chat_proto_depIdxs = []int32{
	7,  // 0: chatpb.GetMessagesResponse.messages:type_name -> chatpb.ChatMessage
	10, // 1: chatpb.GetUserChatsResponse.chats:type_name -> chatpb.ChatPreview
	0,  // 2: chatpb.ChatService.CreateChat:input_type -> chatpb.CreateChatRequest
	2,  // 3: chatpb.ChatService.SendMessage:input_type -> chatpb.SendMessageRequest
	4,  // 4: chatpb.ChatService.GetParticipants:input_type -> chatpb.GetParticipantsRequest
	6,  // 5: chatpb.ChatService.GetMessages:input_type -> chatpb.GetMessagesRequest
	9,  // 6: chatpb.ChatService.GetUserChats:input_type -> chatpb.GetUserChatsRequest
	12, // 7: chatpb.ChatService.MarkChatRead:input_type -> chatpb.MarkChatReadRequest
	14, // 8: chatpb.ChatService.SetChatMatchTags:input_type -> chatpb.SetChatMatchTagsRequest
	16, // 9: chatpb.ChatService.BlockUser:input_type -> chatpb.BlockUserRequest
	18, // 10: chatpb.ChatService.GetBlockStatus:input_type -> chatpb.GetBlockStatusRequest
	20, // 11: chatpb.ChatService.UnblockUser:input_type -> chatpb.UnblockUserRequest
	1,  // 12: chatpb.ChatService.CreateChat:output_type -> chatpb.CreateChatResponse
	3,  // 13: chatpb.ChatService.SendMessage:output_type -> chatpb.SendMessageResponse
	5,  // 14: chatpb.ChatService.GetParticipants:output_type -> chatpb.GetParticipantsResponse
	8,  // 15: chatpb.ChatService.GetMessages:output_type -> chatpb.GetMessagesResponse
	11, // 16: chatpb.ChatService.GetUserChats:output_type -> chatpb.GetUserChatsResponse
	13, // 17: chatpb.ChatService.MarkChatRead:output_type -> chatpb.MarkChatReadResponse
	15, // 18: chatpb.ChatService.SetChatMatchTags:output_type -> chatpb.SetChatMatchTagsResponse
	17, // 19: chatpb.ChatService.BlockUser:output_type -> chatpb.BlockUserResponse
	19, // 20: chatpb.ChatService.GetBlockStatus:output_type -> chatpb.GetBlockStatusResponse
	21, // 21: chatpb.ChatService.UnblockUser:output_type -> chatpb.UnblockUserResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_chatpb_chat_proto_init() }
func file_chatpb_chat_proto_init() {
	if File_chatpb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatpb_chat_proto_rawDesc), len(file_chatpb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatpb_chat_proto_goTypes,
		DependencyIndexes: file_chatpb_chat_proto_depIdxs,
		MessageInfos:      file_chatpb_chat_proto_msgTypes,
	}.Build()
	File_chatpb_chat_proto = out.File
	file_chatpb_chat_proto_goTypes = nil
	file_chatpb_chat_proto_depIdxs = nil
}
