// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: api/proto/matchingpb/matching.proto

package matchingpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchMode int32

const (
	MatchMode_MATCH_MODE_UNSPECIFIED MatchMode = 0
	MatchMode_MATCH_MODE_DEFAULT     MatchMode = 1
	MatchMode_MATCH_MODE_LANGUAGE    MatchMode = 2
	MatchMode_MATCH_MODE_INTEREST    MatchMode = 3
)

// Enum value maps for MatchMode.
var (
	MatchMode_name = map[int32]string{
		0: "MATCH_MODE_UNSPECIFIED",
		1: "MATCH_MODE_DEFAULT",
		2: "MATCH_MODE_LANGUAGE",
		3: "MATCH_MODE_INTEREST",
	}
	MatchMode_value = map[string]int32{
		"MATCH_MODE_UNSPECIFIED": 0,
		"MATCH_MODE_DEFAULT":     1,
		"MATCH_MODE_LANGUAGE":    2,
		"MATCH_MODE_INTEREST":    3,
	}
)

func (x MatchMode) Enum() *MatchMode {
	p := new(MatchMode)
	*p = x
	return p
}

func (x MatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_matchingpb_matching_proto_enumTypes[0].Descriptor()
}

func (MatchMode) Type() protoreflect.EnumType {
	return &file_api_proto_matchingpb_matching_proto_enumTypes[0]
}

func (x MatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMode.Descriptor instead.
func (MatchMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{0}
}

type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mode          MatchMode              `protobuf:"varint,2,opt,name=mode,proto3,enum=matchingpb.MatchMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{0}
}

func (x *JoinQueueRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinQueueRequest) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_MATCH_MODE_UNSPECIFIED
}

type JoinQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueResponse) Reset() {
	*x = JoinQueueResponse{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueResponse) ProtoMessage() {}

func (x *JoinQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueResponse.ProtoReflect.Descriptor instead.
func (*JoinQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{1}
}

func (x *JoinQueueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveQueueRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LeaveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueResponse) Reset() {
	*x = LeaveQueueResponse{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueResponse) ProtoMessage() {}

func (x *LeaveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueResponse.ProtoReflect.Descriptor instead.
func (*LeaveQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveQueueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueRequest) Reset() {
	*x = ListQueueRequest{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueRequest) ProtoMessage() {}

func (x *ListQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueRequest.ProtoReflect.Descriptor instead.
func (*ListQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{4}
}

type ListQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueResponse) Reset() {
	*x = ListQueueResponse{}
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueResponse) ProtoMessage() {}

func (x *ListQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_matchingpb_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueResponse.ProtoReflect.Descriptor instead.
func (*ListQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_matchingpb_matching_proto_rawDescGZIP(), []int{5}
}

func (x *ListQueueResponse) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

var File_api_proto_matchingpb_matching_proto protoreflect.FileDescriptor

const file_api_proto_matchingpb_matching_proto_rawDesc = "" +
	"\n" +
	"#api/proto/matchingpb/matching.proto\x12\n" +
	"matchingpb\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"Y\n" +
	"\x10JoinQueueRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12)\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x15.matchingpb.MatchModeR\x04mode\"#\n" +
	"\x11JoinQueueResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"/\n" +
	"\x11LeaveQueueRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"$\n" +
	"\x12LeaveQueueResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x12\n" +
	"\x10ListQueueRequest\"1\n" +
	"\x11ListQueueResponse\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames*q\n" +
	"\tMatchMode\x12\x1a\n" +
	"\x16MATCH_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MATCH_MODE_DEFAULT\x10\x01\x12\x17\n" +
	"\x13MATCH_MODE_LANGUAGE\x10\x02\x12\x17\n" +
	"\x13MATCH_MODE_INTEREST\x10\x032\xca\x02\n" +
	"\x0fMatchingService\x12f\n" +
	"\tJoinQueue\x12\x1c.matchingpb.JoinQueueRequest\x1a\x1d.matchingpb.JoinQueueResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/matching/join\x12j\n" +
	"\n" +
	"LeaveQueue\x12\x1d.matchingpb.LeaveQueueRequest\x1a\x1e.matchingpb.LeaveQueueResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/matching/leave\x12c\n" +
	"\tListQueue\x12\x1c.matchingpb.ListQueueRequest\x1a\x1d.matchingpb.ListQueueResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/matching/listB9Z7github.com/chimort/course_project2/api/proto/matchingpbb\x06proto3"

var (
	file_api_proto_matchingpb_matching_proto_rawDescOnce sync.Once
	file_api_proto_matchingpb_matching_proto_rawDescData []byte
)

func file_api_proto_matchingpb_matching_proto_rawDescGZIP() []byte {
	file_api_proto_matchingpb_matching_proto_rawDescOnce.Do(func() {
		file_api_proto_matchingpb_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_matchingpb_matching_proto_rawDesc), len(file_api_proto_matchingpb_matching_proto_rawDesc)))
	})
	return file_api_proto_matchingpb_matching_proto_rawDescData
}

var file_api_proto_matchingpb_matching_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_matchingpb_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_matchingpb_matching_proto_goTypes = []any{
	(MatchMode)(0),             // 0: matchingpb.MatchMode
	(*JoinQueueRequest)(nil),   // 1: matchingpb.JoinQueueRequest
	(*JoinQueueResponse)(nil),  // 2: matchingpb.JoinQueueResponse
	(*LeaveQueueRequest)(nil),  // 3: matchingpb.LeaveQueueRequest
	(*LeaveQueueResponse)(nil), // 4: matchingpb.LeaveQueueResponse
	(*ListQueueRequest)(nil),   // 5: matchingpb.ListQueueRequest
	(*ListQueueResponse)(nil),  // 6: matchingpb.ListQueueResponse
}
var file_api_proto_matchingpb_matching_proto_depIdxs = []int32{
	0, // 0: matchingpb.JoinQueueRequest.mode:type_name -> matchingpb.MatchMode
	1, // 1: matchingpb.MatchingService.JoinQueue:input_type -> matchingpb.JoinQueueRequest
	3, // 2: matchingpb.MatchingService.LeaveQueue:input_type -> matchingpb.LeaveQueueRequest
	5, // 3: matchingpb.MatchingService.ListQueue:input_type -> matchingpb.ListQueueRequest
	2, // 4: matchingpb.MatchingService.JoinQueue:output_type -> matchingpb.JoinQueueResponse
	4, // 5: matchingpb.MatchingService.LeaveQueue:output_type -> matchingpb.LeaveQueueResponse
	6, // 6: matchingpb.MatchingService.ListQueue:output_type -> matchingpb.ListQueueResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_matchingpb_matching_proto_init() }
func file_api_proto_matchingpb_matching_proto_init() {
	if File_api_proto_matchingpb_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_matchingpb_matching_proto_rawDesc), len(file_api_proto_matchingpb_matching_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_matchingpb_matching_proto_goTypes,
		DependencyIndexes: file_api_proto_matchingpb_matching_proto_depIdxs,
		EnumInfos:         file_api_proto_matchingpb_matching_proto_enumTypes,
		MessageInfos:      file_api_proto_matchingpb_matching_proto_msgTypes,
	}.Build()
	File_api_proto_matchingpb_matching_proto = out.File
	file_api_proto_matchingpb_matching_proto_goTypes = nil
	file_api_proto_matchingpb_matching_proto_depIdxs = nil
}
